version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'

  app:
    # image: quay.io/foreman/foreman:develop
    &app_base
    entrypoint: [ bin/entry ]
    command: bundle exec bin/rails server -b 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgres://foreman:foreman@db/foreman?pool=5
      - RAILS_ENV=development
      - FOREMAN_RAILS_CACHE_STORE_TYPE=redis
      - FOREMAN_RAILS_CACHE_STORE_URLS=redis://redis:6379/0
      - DYNFLOW_REDIS_URL=redis://redis-tasks:6379/0
      - REDIS_PROVIDER=DYNFLOW_REDIS_URL
    links:
      - db
    ports:
      - 3000:3000
      - 5910-5930:5910-5930
    volumes:
      - './:/myapp'

  redis-cache:
    image: redis

  redis-tasks:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-persistent:/data

volumes:
  db: null
  redis-persistent: null
