FROM ruby:2.7.0

RUN apt-get update -qq && apt-get install -y postgresql-client npm libvirt-dev libsystemd-dev

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -\
    && apt-get update -qq && apt-get install -qq --no-install-recommends \
    nodejs \
    && apt-get upgrade -qq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*\
    &&  npm install -g yarn@1

RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
ENV BUNDLER_VERSION 2.1.4
RUN gem update --system \
    && gem install bundler -v $BUNDLER_VERSION
COPY . /myapp
RUN bundle install
RUN yarn install

# Add a script to be executed every time the container starts.
COPY bin/entry /usr/bin/
RUN chmod +x /usr/bin/entry
ENTRYPOINT ["/usr/bin/entry"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
